graph TD
    arceos_helloworld_v0_1_0[arceos-helloworld v0.1.0] --> axstd_v0_2_0[axstd v0.2.0]
    axstd_v0_2_0[axstd v0.2.0] --> arceos_api_v0_2_0[arceos_api v0.2.0]
    arceos_api_v0_2_0[arceos_api v0.2.0] --> axconfig_v0_2_0[axconfig v0.2.0]
    axconfig_v0_2_0[axconfig v0.2.0] --> axconfig_macros_v0_2_0[axconfig-macros v0.2.0]
    axconfig_macros_v0_2_0[axconfig-macros v0.2.0] --> axconfig_gen_v0_2_0[axconfig-gen v0.2.0]
    arceos_api_v0_2_0[arceos_api v0.2.0] --> axerrno_v0_1_0[axerrno v0.1.0]
    arceos_api_v0_2_0[arceos_api v0.2.0] --> axfeat_v0_2_0[axfeat v0.2.0]
    axfeat_v0_2_0[axfeat v0.2.0] --> axhal_v0_2_0[axhal v0.2.0]
    axhal_v0_2_0[axhal v0.2.0] --> axconfig_v0_2_0[axconfig v0.2.0]
    axhal_v0_2_0[axhal v0.2.0] --> axcpu_v0_2_2[axcpu v0.2.2]
    axcpu_v0_2_2[axcpu v0.2.2] --> loongArch64_v0_2_5[loongArch64 v0.2.5]
    axcpu_v0_2_2[axcpu v0.2.2] --> memory_addr_v0_4_0[memory_addr v0.4.0]
    axcpu_v0_2_2[axcpu v0.2.2] --> page_table_entry_v0_5_5[page_table_entry v0.5.5]
    page_table_entry_v0_5_5[page_table_entry v0.5.5] --> memory_addr_v0_4_0[memory_addr v0.4.0]
    axcpu_v0_2_2[axcpu v0.2.2] --> page_table_multiarch_v0_5_5[page_table_multiarch v0.5.5]
    page_table_multiarch_v0_5_5[page_table_multiarch v0.5.5] --> memory_addr_v0_4_0[memory_addr v0.4.0]
    page_table_multiarch_v0_5_5[page_table_multiarch v0.5.5] --> page_table_entry_v0_5_5[page_table_entry v0.5.5]
    axhal_v0_2_0[axhal v0.2.0] --> axlog_v0_2_0[axlog v0.2.0]
    axlog_v0_2_0[axlog v0.2.0] --> crate_interface_v0_1_4[crate_interface v0.1.4]
    axlog_v0_2_0[axlog v0.2.0] --> kspin_v0_1_1[kspin v0.1.1]
    kspin_v0_1_1[kspin v0.1.1] --> kernel_guard_v0_1_2[kernel_guard v0.1.2]
    kernel_guard_v0_1_2[kernel_guard v0.1.2] --> crate_interface_v0_1_4[crate_interface v0.1.4]
    axhal_v0_2_0[axhal v0.2.0] --> axplat_v0_3_0[axplat v0.3.0]
    axplat_v0_3_0[axplat v0.3.0] --> axplat_macros_v0_1_0[axplat-macros v0.1.0]
    axplat_v0_3_0[axplat v0.3.0] --> crate_interface_v0_1_4[crate_interface v0.1.4]
    axplat_v0_3_0[axplat v0.3.0] --> kspin_v0_1_1[kspin v0.1.1]
    axplat_v0_3_0[axplat v0.3.0] --> memory_addr_v0_4_0[memory_addr v0.4.0]
    axhal_v0_2_0[axhal v0.2.0] --> axplat_loongarch64_qemu_virt_v0_3_0[axplat-loongarch64-qemu-virt v0.3.0]
    axplat_loongarch64_qemu_virt_v0_3_0[axplat-loongarch64-qemu-virt v0.3.0] --> axconfig_macros_v0_2_0[axconfig-macros v0.2.0]
    axplat_loongarch64_qemu_virt_v0_3_0[axplat-loongarch64-qemu-virt v0.3.0] --> axcpu_v0_2_2[axcpu v0.2.2]
    axplat_loongarch64_qemu_virt_v0_3_0[axplat-loongarch64-qemu-virt v0.3.0] --> axplat_v0_3_0[axplat v0.3.0]
    axplat_loongarch64_qemu_virt_v0_3_0[axplat-loongarch64-qemu-virt v0.3.0] --> kspin_v0_1_1[kspin v0.1.1]
    axplat_loongarch64_qemu_virt_v0_3_0[axplat-loongarch64-qemu-virt v0.3.0] --> loongArch64_v0_2_5[loongArch64 v0.2.5]
    axplat_loongarch64_qemu_virt_v0_3_0[axplat-loongarch64-qemu-virt v0.3.0] --> page_table_entry_v0_5_5[page_table_entry v0.5.5]
    axhal_v0_2_0[axhal v0.2.0] --> kernel_guard_v0_1_2[kernel_guard v0.1.2]
    axhal_v0_2_0[axhal v0.2.0] --> memory_addr_v0_4_0[memory_addr v0.4.0]
    axhal_v0_2_0[axhal v0.2.0] --> percpu_v0_2_0[percpu v0.2.0]
    percpu_v0_2_0[percpu v0.2.0] --> percpu_macros_v0_2_0[percpu_macros v0.2.0]
    axfeat_v0_2_0[axfeat v0.2.0] --> axlog_v0_2_0[axlog v0.2.0]
    axfeat_v0_2_0[axfeat v0.2.0] --> axruntime_v0_2_0[axruntime v0.2.0]
    axruntime_v0_2_0[axruntime v0.2.0] --> axconfig_v0_2_0[axconfig v0.2.0]
    axruntime_v0_2_0[axruntime v0.2.0] --> axhal_v0_2_0[axhal v0.2.0]
    axruntime_v0_2_0[axruntime v0.2.0] --> axlog_v0_2_0[axlog v0.2.0]
    axruntime_v0_2_0[axruntime v0.2.0] --> axplat_v0_3_0[axplat v0.3.0]
    axruntime_v0_2_0[axruntime v0.2.0] --> crate_interface_v0_1_4[crate_interface v0.1.4]
    arceos_api_v0_2_0[arceos_api v0.2.0] --> axhal_v0_2_0[axhal v0.2.0]
    arceos_api_v0_2_0[arceos_api v0.2.0] --> axio_v0_1_1[axio v0.1.1]
    axio_v0_1_1[axio v0.1.1] --> axerrno_v0_1_0[axerrno v0.1.0]
    arceos_api_v0_2_0[arceos_api v0.2.0] --> axlog_v0_2_0[axlog v0.2.0]
    arceos_api_v0_2_0[arceos_api v0.2.0] --> axruntime_v0_2_0[axruntime v0.2.0]
    arceos_api_v0_2_0[arceos_api v0.2.0] --> axsync_v0_2_0[axsync v0.2.0]
    axsync_v0_2_0[axsync v0.2.0] --> axtask_v0_2_0[axtask v0.2.0]
    axtask_v0_2_0[axtask v0.2.0] --> axhal_v0_2_0[axhal v0.2.0]
    axsync_v0_2_0[axsync v0.2.0] --> kspin_v0_1_1[kspin v0.1.1]
    axstd_v0_2_0[axstd v0.2.0] --> axerrno_v0_1_0[axerrno v0.1.0]
    axstd_v0_2_0[axstd v0.2.0] --> axfeat_v0_2_0[axfeat v0.2.0]
    axstd_v0_2_0[axstd v0.2.0] --> axio_v0_1_1[axio v0.1.1]
    axstd_v0_2_0[axstd v0.2.0] --> kspin_v0_1_1[kspin v0.1.1]
